### ISSUE TITLE
Файловая система

### ISSUE THREAD

**Issue by alex-chaplygin** [alex-chaplygin/os-pi#23]
Написать программу tools/fs.c, которая форматирует диск как файл (1 команда) и может записывать файлы на диске (2 команда).
Структура диска: (блок 512 байт)
0 блок - суперблок
magic - 0x7171
word - всего блоков на диске (максимум 65535)
word - всего файлов в каталоге (максимум 320 файлов)
byte - размер блока
10 блоков - каталог (16 байт на запись файла)
имя - 12 байт
первый блок - word
всего блоков на файл - word
11 блок
отсюда начинаются данные файлов

Примеры команды:
fs create -o disk -s 1024 // создает диск в файле disk размером 1024 блока
fs write disk 1.txt // записывает на диск в файле disk внешний файл 1.txt

**Comment by zergon321** [comment]
Готово. Код находится в ветке `iss23`. На размер блока ушёл `word`, а не `byte` (число 512 не поместится в 1 байт). 
Использование:
```bash
fs create -o disk -s 1024 #Создать диск.
fs write -d disk -f file.txt #Записать файл на диск.
```
