### ISSUE TITLE
Реорганизация кода

### ISSUE THREAD

**Issue by alex-chaplygin** [alex-chaplygin/os-pi#29]
сделать папки x86 и portable, перенести файлы (через git mv) в эти папки, все что касается архитектуры x86 в папку x86, а общий код включая main - в папку portable. переименовать функции, которые вызываются в main и относятся к архитектуре x86.
в makefile тоже поменять пути или сделать вложенные makefile в папках (посмотри как это делается)
пусть kernel генерируется в каталоге bin
в корневом должно остаться Doxyfile README.md makefile link.ld

**Comment by alex-chaplygin** [comment]
@zergon321 тебе новое задание

**Comment by zergon321** [comment]
А а что относится к x86 помимо всего того, что определено в x86.h и x86.asm?

**Comment by alex-chaplygin** [comment]
подумай сам, что мы брали в документациях по устройствам

**Comment by zergon321** [comment]
Как необходимо переименовать функции, вызываемые в main и относящиеся к x86? Поставить им префикс "x86_"?

**Comment by alex-chaplygin** [comment]
Сами x86 функции переименовывать не надо (если только их можно отнести к общим функциям).
Надо сделать так, чтобы действие (название) было общим для всех архитектур, например инициализация памяти, инициализация прерываний

**Comment by zergon321** [comment]
Готово. Вот [pull request](https://github.com/alex-chaplygin/os-pi/pull/33/files).

**Comment by alex-chaplygin** [comment]
Максим, не надо делать pull реквесты, выкладывай ветку

**Comment by zergon321** [comment]
Ветка [iss29](https://github.com/alex-chaplygin/os-pi/tree/iss29).
